
#pragma once

#define LEN_STRT                    5
#define LEN_CMD                     2
#define LEN_PARAM                   4
#define LEN_PAD                     102400
#define SIZE_BLOCK                  1024*5

enum _eCMD
{
	CMD_ISIDLE = 1,
	CMD_RESET,
	CMD_STARTCRC,
	CMD_STOP,
	CMD_PREPARET2D,
	CMD_PREPARETXT,
	CMD_SCREENEE,
	CMD_SCREENEEID,
	CMD_SCREENINGDATE,
	CMD_FILE_NAME,
	CMD_FILE_SIZE,
	CMD_FILE_CONTENT,
	CMD_FILE_END,
	CMD_NOW_IDLE,
	CMD_NOW_BUSY,
	CMD_STILL_ALIVE,
	CMD_MV_COMPLETED,
	CMD_STATE_IDLE,
	CMD_STATE_BATCH,
	CMD_STATE_REARRANGE,
	CMD_STATE_NOMALIZE,
	CMD_STATE_PARETO,
	CMD_STATE_WEIGHTING,
	CMD_STATE_COMPLETED,
	CMD_SCREENEE_DONE,
	CMD_SCREENEE_FILE_DONE,
};

#define PORT_MV 25000
#define PORT_DB 25001